{"uuid": "33a92094-3ddc-44c6-8fa3-cc5ba3a8259b", "children": ["9cf83933-ddd5-47d4-ab51-f3c1d7547179"], "befores": [{"name": "with_open_lottery_page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\caipiao\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\caipiao\\case\\caipiao-client\\conftest.py\", line 10, in with_open_lottery_page\n    cpclogin.login()\n  File \"d:\\caipiao\\biz\\caipiao_client\\login_page.py\", line 17, in login\n    self.open_login_url(ip=240)\n  File \"d:\\caipiao\\biz\\caipiao_client\\login_page.py\", line 14, in open_login_url\n    self.open(login_url)\n  File \"d:\\caipiao\\base\\box.py\", line 906, in open\n    self.base_driver.navigate(url)\n  File \"d:\\caipiao\\base\\box.py\", line 262, in navigate\n    self._base_driver.get(url)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568441681099, "stop": 1568441681101}], "start": 1568441681099, "stop": 1568441681159}