{"uuid": "5ec4e1be-3bd7-4b8f-8520-a644ae6a63e1", "children": ["2b4dab16-9509-44df-bd68-9ddb231c637b"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\coding\\case\\conftest.py\", line 7, in with_login_cpc\n    cpclogin.login()\n  File \"d:\\coding\\biz\\caipiao_client\\login_page.py\", line 17, in login\n    self.open_login_url(ip=240)\n  File \"d:\\coding\\biz\\caipiao_client\\login_page.py\", line 14, in open_login_url\n    self.open(login_url)\n  File \"d:\\coding\\base\\box.py\", line 906, in open\n    self.base_driver.navigate(url)\n  File \"d:\\coding\\base\\box.py\", line 262, in navigate\n    self._base_driver.get(url)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568464826831, "stop": 1568464826834}], "start": 1568464826831, "stop": 1568464826905}