{"uuid": "b68af2f0-4c19-41ac-8cff-e48b55322572", "children": ["166328aa-6a97-4346-8ca8-abcfccdeb1f0"], "befores": [{"name": "setup_teardown", "status": "passed", "start": 1568443177356, "stop": 1568443177362}], "afters": [{"name": "setup_teardown::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\caipiao\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 786, in _teardown_yield_fixture\n    next(it)\n  File \"d:\\caipiao\\case\\caipiao-client\\conftest.py\", line 13, in setup_teardown\n    BasePage().close()\n  File \"d:\\caipiao\\base\\box.py\", line 922, in close\n    self.base_driver.close_browser()\n  File \"d:\\caipiao\\base\\box.py\", line 276, in close_browser\n    self._base_driver.close()\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568443177452, "stop": 1568443177455}], "start": 1568443177355, "stop": 1568443177455}