{"uuid": "5b155c86-855c-46ae-8932-a942ca09413f", "children": ["9e6fc55d-760e-4fa6-a785-c9e3dd736119"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\caipiao\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 778, in call_fixture_func\n    res = fixturefunc(**kwargs)\n  File \"d:\\caipiao\\case\\conftest.py\", line 9, in with_login_cpc\n    cpclogin.login()\n  File \"d:\\caipiao\\biz\\caipiao_client\\login_page.py\", line 17, in login\n    self.open_login_url(ip=240)\n  File \"d:\\caipiao\\biz\\caipiao_client\\login_page.py\", line 14, in open_login_url\n    self.open(login_url)\n  File \"d:\\caipiao\\base\\box.py\", line 906, in open\n    self.base_driver.navigate(url)\n  File \"d:\\caipiao\\base\\box.py\", line 262, in navigate\n    self._base_driver.get(url)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568381264381, "stop": 1568381264386}], "start": 1568381264381, "stop": 1568381264473}