{"uuid": "aaf9d4ab-04b1-4c75-a861-ecbc2e25ea89", "children": ["cf8cc795-2af7-4153-8a8a-a7080373fac8"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\coding\\case\\conftest.py\", line 10, in with_login_cpc\n    cpclogin.open_login_url()\n  File \"d:\\coding\\biz\\caipiao_client\\login_page.py\", line 15, in open_login_url\n    self.open(login_url)\n  File \"d:\\coding\\base\\box.py\", line 907, in open\n    self.base_driver.navigate(url)\n  File \"d:\\coding\\base\\box.py\", line 263, in navigate\n    self._base_driver.get(url)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568472771277, "stop": 1568472771292}], "start": 1568472771277, "stop": 1568472771375}