{"uuid": "44bcf5bd-9240-45ca-adb5-8d6a72aa08e5", "children": ["800488f0-8128-489f-a6b5-1b4b21616d86"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"d:\\python37-32\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37-32\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\coding\\case\\conftest.py\", line 10, in with_login_cpc\n    cpclogin = CpCLoginPage(BoxDriver())\n  File \"d:\\coding\\base\\box.py\", line 58, in __init__\n    driver = webdriver.Chrome(chrome_options=profile)\n  File \"d:\\python37-32\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"d:\\python37-32\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 83, in start\n    os.path.basename(self.path), self.start_error_message)\n"}, "start": 1568962981120, "stop": 1568962981126}], "start": 1568962981120, "stop": 1568962981249}