{"uuid": "44bb5e2b-df7a-45e0-9813-0ddf0f1d676e", "children": ["168a681e-f70f-4f3f-bfd7-38a817e962af"], "befores": [{"name": "setup_teardown", "status": "passed", "start": 1568443181721, "stop": 1568443181724}], "afters": [{"name": "setup_teardown::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"d:\\caipiao\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 786, in _teardown_yield_fixture\n    next(it)\n  File \"d:\\caipiao\\case\\caipiao-client\\conftest.py\", line 13, in setup_teardown\n    BasePage().close()\n  File \"d:\\caipiao\\base\\box.py\", line 922, in close\n    self.base_driver.close_browser()\n  File \"d:\\caipiao\\base\\box.py\", line 276, in close_browser\n    self._base_driver.close()\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568443181811, "stop": 1568443181814}], "start": 1568443181721, "stop": 1568443181814}