{"uuid": "0bd324d9-ab35-4b99-8fda-ee9804adaa81", "children": ["3a1b934f-e37a-49c2-b627-b810d5697faa"], "befores": [{"name": "with_login_cpc", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\n\n", "trace": "  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 927, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"d:\\coding\\case\\conftest.py\", line 7, in with_login_cpc\n    cpclogin.login()\n  File \"d:\\coding\\biz\\caipiao_client\\login_page.py\", line 17, in login\n    self.open_login_url(ip=240)\n  File \"d:\\coding\\biz\\caipiao_client\\login_page.py\", line 14, in open_login_url\n    self.open(login_url)\n  File \"d:\\coding\\base\\box.py\", line 906, in open\n    self.base_driver.navigate(url)\n  File \"d:\\coding\\base\\box.py\", line 262, in navigate\n    self._base_driver.get(url)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 333, in get\n    self.execute(Command.GET, {'url': url})\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\dajun\\documents\\caipiao\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1568464918152, "stop": 1568464918155}], "start": 1568464918152, "stop": 1568464918232}